import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation} from '../src/simulation.js';import {Army} from '../src/army.js';import {updateRun} from '../src/run-stats.js';
const rng=()=>{let n=88;return()=>((n=(n*1664525+1013904223)>>>0)/4294967296);};
const advance=(s,n)=>{if(n!==undefined){for(let i=0;i<n;i++)s.update(.05);return;}for(let i=0;i<100&&s.hordes.some(h=>!h.alive);i++)s.update(.05);};
test('A/D/E: build, death snapshot, same-world respawn, records and killer memory',()=>{const s=new Simulation(rng()),p=s.player,k=s.hordes[1],world=s.map,players=s.hordes;advance(s,10);s.recruit(p,100);const peak=p.units.length;assert.equal(p.records.largestArmy,peak);p.run.kills=3;updateRun(p,s.time);s.damage(p,9999,k);const survival=p.lastRun.survival;assert.ok(survival>0);assert.equal(p.lastRun.kills,3);assert.equal(p.latestKiller.id,k.id);assert.equal(p.units.length,0);advance(s);assert.equal(s.map,world);assert.equal(s.hordes,players);assert.equal(p.alive,true);assert.equal(p.run.kills,0);assert.equal(p.score,0);assert.ok(p.run.survival<.2);assert.equal(p.records.largestArmy,peak);assert.equal(p.records.bestKills,3);assert.equal(p.records.runsFinished,1);assert.equal(p.latestKiller.name,k.name);s.recruit(p,2);assert.ok(p.units.length>=6);});
test('B: surviving armies keep fighting while human is dead',()=>{const s=new Simulation(rng()),a=s.hordes[1],b=s.hordes[2];s.time=100;a.x=b.x=1000;a.y=b.y=1000;a.units=new Army(50);b.units=new Army(50);a.think=b.think=10;a.target=b.target=null;const before=a.units.length;s.damage(s.player,9999,b);s.update(.05);assert.equal(s.player.alive,false);assert.ok(a.units.length<before);assert.equal(s.ended,false);assert.ok(s.time>100);});
test('C/H/I: 50 cycles across 12 participants preserve population and bounded state',()=>{const s=new Simulation(rng()),map=s.map,ids=s.hordes.map(h=>h.id);assert.equal(ids.length,12);for(let cycle=0;cycle<50;cycle++){for(const h of s.hordes){s.recruit(h,20);s.damage(h,99999);}assert.equal(s.hordes.filter(h=>h.alive).length,0);advance(s);assert.equal(s.hordes.length,12);assert.equal(s.hordes.filter(h=>h.alive).length,12);assert.deepEqual(s.hordes.map(h=>h.id),ids);assert.equal(new Set(s.rank().map(h=>h.id)).size,12);assert.equal(s.map,map);assert.equal(s.ended,false);assert.ok(s.effects.length<=100);assert.ok(s.fallen.length<=4);assert.ok(s.resources.every(r=>!r.owner||r.owner.alive));for(const h of s.hordes){assert.equal(h.run.kills,0);assert.equal(h.run.id,cycle+2);assert.equal(h.units.length,h.startingArmy);assert.equal(h.mount,null);assert.equal(h.run.endedAt,null);assert.ok(Number.isFinite(h.x));}}const bot=s.hordes[1],x=bot.x,y=bot.y;advance(s,10);assert.ok(bot.x!==x||bot.y!==y);});
test('F/G: one-use debug reward, configured percentage, cooldown and normal fallback',()=>{const s=new Simulation(rng(),'vikings','hard',{rewardedRecoveryEnabled:true,rewardedRecoveryChance:1,rewardedRecoveryPercentage:.5,rewardedRecoveryCooldown:120}),p=s.player;s.recruit(p,96);s.damage(p,9999);assert.equal(p.lastRun.armyBeforeDeath,100);assert.equal(s.lifecycle.debugComplete(p),true);assert.equal(s.lifecycle.debugComplete(p),false);advance(s);assert.equal(p.units.length,50);s.damage(p,9999);assert.equal(s.lifecycle.debugComplete(p),false);advance(s);assert.equal(p.units.length,4);const normal=new Simulation(rng());normal.damage(normal.player,9999);assert.equal(normal.lifecycle.debugComplete(normal.player),false);advance(normal);assert.equal(normal.player.units.length,4);});
test('spawn search is bounded and maximizes clearance with invulnerable fallback',()=>{const s=new Simulation(rng()),p=s.player;for(const h of s.hordes.slice(1)){h.x=h.y=3000;h.units=new Army(1000);}s.damage(p,9999);const spot=s.lifecycle.safestSpawn(p);assert.ok(Math.hypot(spot.x-3000,spot.y-3000)>1000);advance(s);assert.ok(p.protectedUntil>s.time);});
test('run-owned loot and siege claims cannot leak into a new life',()=>{const s=new Simulation(rng()),p=s.player,enemy=s.hordes[1];s.damage(enemy,3,p);const loot=s.resources.find(r=>r.owner===p),v=s.spawnResource(p.x,p.y,'village',{assailant:p,progress:5});s.damage(p,9999,enemy);assert.equal(loot.owner,null);assert.equal(v.assailant,null);assert.equal(v.progress,0);const old=p.run.survival;advance(s);assert.ok(p.run.survival<old+1);assert.equal(p.fedUntil,0);assert.equal(p.growthUntil,0);});

test('gradual attrition preserves meaningful recovery from previous run peak',()=>{const s=new Simulation(rng(),'vikings','hard',{rewardedRecoveryEnabled:true,rewardedRecoveryChance:1}),p=s.player;s.recruit(p,96);s.damage(p,290);assert.ok(p.alive);s.damage(p,9999);assert.equal(s.lifecycle.debugComplete(p),true);advance(s);assert.equal(p.units.length,50);});

test('failed, unavailable and expired offers fall back without duplicate recovery',()=>{for(const chance of [0,1]){const s=new Simulation(rng(),'vikings','hard',{rewardedRecoveryEnabled:true,rewardedRecoveryChance:chance}),p=s.player;s.damage(p,9999);const offer=s.lifecycle.recovery.offers.get(p.id);if(chance===0)assert.equal(offer,undefined);else assert.equal(s.lifecycle.recovery.complete(p,offer.token,false),false);advance(s);assert.equal(p.units.length,4);assert.equal(s.lifecycle.debugComplete(p),false);if(offer)assert.equal(s.lifecycle.recovery.complete(p,offer.token,true),false);}});

test('leaderboard ranks current army descending regardless of score, with stable ties',()=>{const s=new Simulation(rng()),a=s.player,b=s.hordes[1],c=s.hordes[2];s.hordes=[c,b,a];a.units=new Army(10);a.score=999999;b.units=new Army(20);b.score=0;c.units=new Army(20);assert.deepEqual(s.rank().map(h=>h.id),[b.id,c.id,a.id]);b.alive=false;assert.deepEqual(s.rank().map(h=>h.id),[c.id,a.id]);});

test('contact hits immediately, repeats at combat cadence and re-entry hits promptly',()=>{const s=new Simulation(rng()),a=s.player,b=s.hordes[1];s.hordes=[a,b];s.time=100;a.units=new Army(50);b.units=new Army(50);b.x=a.x+50;b.y=a.y;s.updateBattles();const n=a.units.length;assert.ok(n<50);s.time+=.05;s.updateBattles();assert.equal(a.units.length,n);s.time+=.32;s.updateBattles();assert.ok(a.units.length<n);b.x+=2000;s.updateBattles();assert.equal(s.contactCooldowns.size,0);b.x=a.x+50;const next=a.units.length;s.updateBattles();assert.ok(a.units.length<next);});
test('moving toward rival ends own protection but retreating preserves it',()=>{const s=new Simulation(rng()),p=s.player,b=s.hordes[1];b.x=p.x+40;b.y=p.y;s.releaseOffensiveProtection({x:-1000,y:0});assert.ok(p.protectedUntil>s.time);s.releaseOffensiveProtection({x:1000,y:0});assert.equal(p.protectedUntil,s.time);assert.equal(s.canFight(p,b),true);b.protectedUntil=s.time+3;assert.equal(s.canFight(p,b),false);});
test('respawn protection is short and death clears pair combat cooldowns',()=>{const s=new Simulation(rng()),p=s.player;s.time=100;s.contactCooldowns.set(p.id+':'+s.hordes[1].id,101);s.damage(p,9999);assert.equal(s.contactCooldowns.size,0);advance(s);assert.ok(Math.abs(p.protectedUntil-s.time-3)<.0001);});
