export const MUSIC_PATTERN=[57,60,64,69,64,60,62,64,55,59,62,67,62,59,60,62,53,57,60,65,60,57,59,60,52,55,59,64,59,55,57,59];
export function readAudioSettings(storage){try{const s=JSON.parse(storage.getItem('hordes.audio.v1')||'null');return{muted:!!s?.muted,music:Number.isFinite(s?.music)?Math.max(0,Math.min(1,s.music)):.22,sfx:Number.isFinite(s?.sfx)?Math.max(0,Math.min(1,s.sfx)):.65};}catch{return{muted:false,music:.22,sfx:.65};}}
export class GameAudio{
 constructor(settings=null){if(!settings){try{settings=readAudioSettings(globalThis.localStorage);}catch{settings=readAudioSettings(null);}}this.settings=settings;this.ctx=null;this.playing=false;this.nextBeat=0;this.beat=0;this.cooldowns=new Map();this.voices=0;}
 async unlock(){try{if(!this.ctx){const AudioCtor=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AudioCtor)return;this.ctx=new AudioCtor();this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.sfx=this.ctx.createGain();this.music.connect(this.master);this.sfx.connect(this.master);this.master.connect(this.ctx.destination);this.apply();}if(this.ctx.state==='suspended')await this.ctx.resume();}catch{/* The game remains playable without browser audio support. */}}
 apply(){if(this.ctx){const t=this.ctx.currentTime;this.master.gain.setTargetAtTime(this.settings.muted?0:1,t,.025);this.music.gain.setTargetAtTime(this.playing?this.settings.music:0,t,.025);this.sfx.gain.setTargetAtTime(this.settings.sfx,t,.025);}try{globalThis.localStorage.setItem('hordes.audio.v1',JSON.stringify(this.settings));}catch{}}
 setPlaying(value){this.playing=value;if(this.ctx){this.nextBeat=this.ctx.currentTime+.06;this.beat=0;this.music.gain.cancelScheduledValues(this.ctx.currentTime);this.music.gain.setTargetAtTime(value?this.settings.music:0,this.ctx.currentTime,.06);}}
 tone(frequency,duration=.15,volume=.15,type='triangle',bus=this.sfx,when=this.ctx?.currentTime||0){if(!this.ctx||this.voices>=48)return;const oscillator=this.ctx.createOscillator(),gain=this.ctx.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,when);gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,volume),when+.008);gain.gain.exponentialRampToValueAtTime(.0001,when+duration);oscillator.connect(gain);gain.connect(bus);oscillator.start(when);oscillator.stop(when+duration+.02);this.voices++;oscillator.onended=()=>{this.voices--;oscillator.disconnect();gain.disconnect();};}
 noise(duration=.08,volume=.12,when=this.ctx?.currentTime||0){if(!this.ctx||this.voices>=48)return;const source=this.ctx.createBufferSource(),gain=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();const buffer=this.ctx.createBuffer(1,Math.ceil(this.ctx.sampleRate*duration),this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);source.buffer=buffer;filter.type='bandpass';filter.frequency.value=1200;source.connect(filter);filter.connect(gain);gain.gain.setValueAtTime(volume,when);gain.connect(this.sfx);source.start(when);this.voices++;source.onended=()=>{this.voices--;source.disconnect();filter.disconnect();gain.disconnect();};}
 play(kind){if(!this.ctx||this.ctx.state!=='running'||this.settings.muted)return;const now=this.ctx.currentTime,cooldown={pickup:.24,food:.35,battle:.16,horse:.8,village:1,conquest:.6}[kind]||.2;if(now-(this.cooldowns.get(kind)??-Infinity)<cooldown)return;this.cooldowns.set(kind,now);const sequence=(notes,gap=.09)=>notes.forEach((n,i)=>this.tone(n,.18,.13,'triangle',this.sfx,now+i*gap));if(kind==='pickup'){this.tone(240,.1,.035,'sine');this.tone(300,.11,.022,'sine',this.sfx,now+.04);}else if(kind==='food'){this.tone(175,.13,.035,'sine');this.tone(220,.12,.018,'sine',this.sfx,now+.045);}else if(kind==='battle'){this.noise(.055,.16);this.tone(145,.09,.16,'triangle');this.tone(1600,.04,.05,'sine');}else if(kind==='horse'){this.tone(100,.07,.16);this.tone(135,.07,.13,'triangle',this.sfx,now+.11);}else if(kind==='growth')sequence([330,440,550,660]);else if(kind==='village'||kind==='conquest')sequence([261.63,329.63,392,523.25]);else if(kind==='victory')sequence([261.63,329.63,392,523.25,659.25,783.99],.13);else if(kind==='death')sequence([330,277,220,165],.16);else if(kind==='start')sequence([220,330,440]);}
 update(){if(!this.ctx||!this.playing||this.ctx.state!=='running'||this.settings.muted||!this.settings.music)return;const now=this.ctx.currentTime;if(this.nextBeat<now-.4)this.nextBeat=now+.04;let scheduled=0;while(this.nextBeat<now+.12&&scheduled++<2){const note=MUSIC_PATTERN[this.beat%MUSIC_PATTERN.length],frequency=440*2**((note-69)/12);this.tone(frequency,.34,.11,'triangle',this.music,this.nextBeat);if(this.beat%4===0){this.tone(frequency/2,.65,.075,'sine',this.music,this.nextBeat);this.tone(75,.09,.07,'sine',this.music,this.nextBeat);}this.beat++;this.nextBeat+=.27;}}
}
