import {loadPilotAssets} from './pilot-assets.js';
import {translate,readLanguage} from './i18n.js';
import {GameAudio} from './audio.js';
import {DIFFICULTIES,difficultyForMatch,readProgress,saveProgress} from './progression.js';
import {Simulation} from './simulation.js';
import {Renderer} from './renderer.js';
import {CONFIG,villageReward,FACTIONS} from './config.js';
const $=id=>document.getElementById(id),canvas=$('arena'),renderer=new Renderer(canvas),audio=new GameAudio(),keys=new Set();
$('play').disabled=true;try{await loadPilotAssets();}catch(error){console.warn('Pilot art could not load; procedural fallback active.',error);}$('play').disabled=false;
let sim=new Simulation(),state='menu',last=0,hudTimer=0,pointer=null,touchOrigin=null,completed=0,accumulator=0,lastBoard='',lastBuffs='',language='en',lastRunId=0;
try{completed=readProgress(localStorage);language=readLanguage(localStorage);}catch{}
const t=(key,vars)=>translate(language,key,vars);
const nameOf=h=>h===sim.player?t('you'):h.name;
const opponentName=name=>name===sim.player.name?t('you'):name;
function nextDifficulty(){return $('difficulty').value==='auto'?difficultyForMatch(completed):$('difficulty').value;}
function updateDifficultyLabel(){$('difficultyHint').textContent=t($('difficulty').value==='auto'?'next':'selected',{level:t(nextDifficulty())});}
function clearInput(){pointer=null;touchOrigin=null;keys.clear();accumulator=0;}
function placeAudio(inMenu){(inMenu?$('menu'):document.body).append($('audioControls'));}
function menu(paused=false){placeAudio(true);$('menu').hidden=false;$('hud').hidden=true;$('deathNotice').hidden=true;$('menu').classList.toggle('is-paused',paused);$('pausedNotice').hidden=!paused;$('resume').hidden=!paused;$('play').hidden=paused;$('play').textContent=t('play');}
function start(){placeAudio(false);lastRunId=1;$('fallenBanner').hidden=true;sim=new Simulation(Math.random,$('faction').value,nextDifficulty(),new URLSearchParams(location.search).has('debugRecovery')?{rewardedRecoveryEnabled:true,rewardedRecoveryChance:1,respawnDelay:20}:{});clearInput();lastBoard='';lastBuffs='';renderer.camera={x:sim.player.x,y:sim.player.y};state='playing';$('menu').hidden=true;$('deathNotice').hidden=true;$('hud').hidden=false;audio.unlock().then(()=>{audio.setPlaying(state==='playing');audio.play('start');});updateHud();}
function pause(){if(state==='playing'){state='paused';audio.setPlaying(false);clearInput();menu(true);}else if(state==='paused'){placeAudio(false);state='playing';clearInput();$('menu').hidden=true;$('hud').hidden=false;audio.unlock().then(()=>audio.setPlaying(state==='playing'));}}
function updateHud(){
 const order=sim.rank(),leaders=order.slice(0,5);if(sim.player.alive&&!leaders.includes(sim.player))leaders.push(sim.player);
 const boardKey=language+'|'+leaders.map(h=>[h.name,h.units.length,h.opponents.join(','),h.siege?Math.floor(h.siege.village.progress):'',h.siege?.contested].join(':')).join('|');
 if(boardKey!==lastBoard){lastBoard=boardKey;$('board').replaceChildren(...leaders.map(h=>{const row=document.createElement('li'),name=document.createElement('span'),count=document.createElement('b'),position=order.indexOf(h)+1;if(h===sim.player)row.className='you';name.textContent=(position===1?'👑 '+t('title_'+h.faction)+' ':position+'. ')+nameOf(h);row.title=t('faction_'+h.faction);if(position===1)row.classList.add('first');count.textContent=h.units.length;if(h.opponents.length||h.siege){const battle=document.createElement('small');battle.className='battle-label';battle.textContent=h.opponents.length?'⚔ '+t('vs')+' '+h.opponents.map(opponentName).join(', '):h.siege.contested?'⚔ '+t('contested'):'⚔ '+t('village')+' · '+Math.floor(h.siege.village.progress/CONFIG.villageDuration*100)+'%';name.append(battle);}row.append(name,count);return row;}));}
 const recent=sim.effects.findLast(e=>e.kind==='notice'&&e.key==='absorbed'&&e.life>0)||sim.effects.findLast(e=>e.kind==='notice'&&e.key==='lostSoldiers'&&e.life>0)||sim.effects.findLast(e=>e.kind==='notice'&&e.life>0);$('collectionNotice').hidden=!recent;if(recent){$('collectionNotice').style.color=recent.color;$('collectionNotice').textContent=t(recent.key,{...recent.data,name:opponentName(recent.data.name)});}$('factionName').textContent=t('faction_'+sim.player.faction).toUpperCase()+' · '+t(sim.difficulty).toUpperCase();$('size').textContent=sim.player.units.length;$('bestArmy').textContent=t('best')+' '+sim.player.records.largestArmy;$('runKills').textContent=sim.player.run.kills;
 const p=sim.player,buffs=[p.fedUntil>sim.time?'▣ '+t('fed')+' · '+Math.ceil(p.fedUntil-sim.time)+'s':'',p.speedUntil>sim.time?'♞ '+t('speed')+' +45% · '+Math.ceil(p.speedUntil-sim.time)+'s':'',p.growthUntil>sim.time?'✦ '+t('growth')+' ×2 · '+Math.ceil(p.growthUntil-sim.time)+'s':'',p.siege?(p.siege.contested?'⌂ '+t('assaultContested'):'⌂ '+t('assault')+' '+Math.ceil(CONFIG.villageDuration-p.siege.village.progress)+'s → +'+villageReward(p.units.length)*(p.growthUntil>sim.time?2:1)):'','⚔ '+p.conquests%CONFIG.conquestsForGrowth+'/3 '+t('conquests')+' → ×2'].filter(Boolean).join('   |   ');
 if(buffs!==lastBuffs){$('buffs').textContent=buffs;lastBuffs=buffs;}const seconds=Math.floor(p.run.survival);$('clock').textContent=Math.floor(seconds/60).toString().padStart(2,'0')+':'+(seconds%60).toString().padStart(2,'0');$('toast').textContent=sim.time<p.protectedUntil?t('protection',{seconds:Math.ceil(p.protectedUntil-sim.time)}):p.units.length>CONFIG.maxVisibleSoldiers?t('squads',{count:p.units.length.toLocaleString(language)}):'';
 $('deathNotice').hidden=p.alive;$('debugDie').disabled=!p.alive;const recovery=sim.lifecycle.recovery.offers.get(p.id);$('debugRecover').hidden=!recovery||!new URLSearchParams(location.search).has('debugRecovery');if(!p.alive){$('deathText').textContent=t('runEnded')+' · '+t('killedBy',{name:p.latestKiller?.name||'—'})+' · '+t('respawning',{seconds:Math.max(0,Math.ceil(p.respawnAt-sim.time))});$('runSummary').textContent=t('runSummary',{army:p.lastRun.largestArmy,time:Math.floor(p.lastRun.survival),kills:p.lastRun.kills});}
 $('killerMemory').hidden=!p.latestKiller;$('killerMemory').textContent=p.latestKiller?t('killedBy',{name:p.latestKiller.name}):'';
 if(p.run.id!==lastRunId){lastRunId=p.run.id;clearInput();renderer.camera={x:p.x,y:p.y};lastBoard='';}

}
function updateAudioLabel(){$('audioLabel').textContent=(audio.settings.muted?'🔇 ':'♪ ')+t('sound');}
function applyLanguage(){document.documentElement.lang=language;renderer.language=language;for(const element of document.querySelectorAll('[data-i18n]'))element.textContent=t(element.dataset.i18n);for(const button of document.querySelectorAll('[data-lang]'))button.setAttribute('aria-pressed',String(button.dataset.lang===language));for(const option of $('faction').options)option.textContent=t('faction_'+option.value);for(const option of $('difficulty').options)option.textContent=t(option.value==='auto'?'auto':option.value+'Option');$('faction').setAttribute('aria-label',t('faction'));$('difficulty').setAttribute('aria-label',t('difficulty'));$('pause').setAttribute('aria-label',t('pause'));$('musicVolume').setAttribute('aria-label',t('musicVolume'));$('sfxVolume').setAttribute('aria-label',t('sfxVolume'));$('resume').textContent=t('resume');$('play').textContent=t(state==='paused'?'newMatch':'play');lastBoard='';lastBuffs='';updateDifficultyLabel();updateAudioLabel();if(state==='playing'||state==='paused')updateHud();}
for(const id of Object.keys(FACTIONS)){const option=document.createElement('option');option.value=id;$('faction').append(option);}
$('faction').onchange=()=>{if(state==='menu')sim=new Simulation(Math.random,$('faction').value);};
for(const button of document.querySelectorAll('[data-lang]'))button.onclick=()=>{language=button.dataset.lang;try{localStorage.setItem('hordes.language.v1',language);}catch{}applyLanguage();};
$('resetTraining').onclick=()=>{completed=0;try{saveProgress(localStorage,0);}catch{}$('difficulty').value='auto';updateDifficultyLabel();};$('difficulty').onchange=updateDifficultyLabel;$('play').onclick=start;$('debugDie').hidden=!new URLSearchParams(location.search).has('debugRecovery');$('debugDie').onclick=()=>{sim.recruit(sim.player,96);sim.damage(sim.player,1e9,sim.hordes[1]);updateHud();};$('debugRecover').onclick=()=>sim.lifecycle.debugComplete(sim.player);$('pause').onclick=pause;$('resume').onclick=pause;
addEventListener('resize',()=>renderer.resize());addEventListener('blur',()=>{if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key==='Escape')pause();keys.add(e.key.toLowerCase());});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;canvas.setPointerCapture(e.pointerId);if(e.pointerType!=='mouse')touchOrigin={x:e.clientX,y:e.clientY};pointer={x:e.clientX,y:e.clientY,touch:e.pointerType!=='mouse'};});canvas.addEventListener('pointermove',e=>{if(state!=='playing')return;if(e.pointerType==='mouse'||touchOrigin)pointer={x:e.clientX,y:e.clientY,touch:e.pointerType!=='mouse'};});function release(e){if(e.pointerType!=='mouse'){pointer=null;touchOrigin=null;}}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',()=>{pointer=null;touchOrigin=null;});canvas.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse')pointer=null;});
function input(){if(!sim.player.alive)return{x:0,y:0};let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(x||y)return{x:x*1000,y:y*1000};if(!pointer)return{x:0,y:0};if(pointer.touch&&touchOrigin)return{x:(pointer.x-touchOrigin.x)*8,y:(pointer.y-touchOrigin.y)*8};return{x:(pointer.x-renderer.w/2)/renderer.zoom+renderer.camera.x-sim.player.x,y:(pointer.y-renderer.h/2)/renderer.zoom+renderer.camera.y-sim.player.y};}
function frame(ms){const dt=Math.min(.1,(ms-last)/1000||0);last=ms;if(state==='playing'){accumulator+=dt;let steps=0;while(accumulator>=1/30&&steps<3){sim.update(1/30,input());for(const sound of sim.audioEvents.splice(0))audio.play(sound);accumulator-=1/30;steps++;}hudTimer+=dt;if(hudTimer>.1){updateHud();hudTimer=0;}}const fallen=sim.fallen?.at(-1);$('fallenBanner').hidden=!fallen||sim.time-fallen.time>4;if(fallen)$('fallenBanner').textContent='♛ ✝ '+t('fell',{name:nameOf(fallen.horde)});audio.update();renderer.draw(sim,sim.time+(state==='playing'?accumulator:0),dt,state==='playing'?accumulator*30:1);requestAnimationFrame(frame);}
$('muteAudio').checked=audio.settings.muted;$('musicVolume').value=audio.settings.music;$('sfxVolume').value=audio.settings.sfx;
function updateAudio(){audio.settings.muted=$('muteAudio').checked;audio.settings.music=Number($('musicVolume').value);audio.settings.sfx=Number($('sfxVolume').value);audio.apply();updateAudioLabel();}
for(const id of ['muteAudio','musicVolume','sfxVolume'])$(id).addEventListener('input',()=>{audio.unlock();updateAudio();});updateAudio();menu(false);applyLanguage();requestAnimationFrame(frame);
