// Bitfolk pilot SVGs are preserved byte-for-byte; only cached display frames are derived.
export const PILOT_FILES={warrior:'viking-warrior.svg',leader:'viking-leader.svg',tree:'pine-tree.svg',rock:'rock.svg',town:'town-hall.svg'};
export const pilotImages={};
export async function loadPilotAssets(){await Promise.all(Object.entries(PILOT_FILES).map(async([key,file])=>{const image=new Image();image.src=new URL('../assets/'+file,import.meta.url).href;await image.decode();const bitmap=document.createElement('canvas');bitmap.width=bitmap.height=key==='town'?384:256;const c=bitmap.getContext('2d');const ratio=key==='town'?205/224:1;c.drawImage(image,0,(bitmap.height-bitmap.height*ratio)/2,bitmap.width,bitmap.height*ratio);pilotImages[key]=bitmap;}));}
export function pilotCharacter(leader,mounted,frame,facing){const image=pilotImages[leader?'leader':'warrior'];if(!image)return null;const canvas=document.createElement('canvas');canvas.width=leader?220:96;canvas.height=leader?272:120;const c=canvas.getContext('2d');c.scale(leader?2:1.5,leader?2:1.5);c.translate(leader?55:32,leader?68:40);c.scale(facing,1);const walk=frame>0&&frame<4,worried=frame>=12&&frame<16,attack=frame>=4&&frame<8,fall=frame>=16;const gait=walk||worried?Math.sin((frame%4)*Math.PI/2):0,collapse=fall?Math.min(1,(frame-16)/3):0;
 c.fillStyle='#10272066';c.beginPath();c.ellipse(0,leader?25:16,mounted?35:leader?25:17,6,0,0,7);c.fill();c.translate(attack?Math.sin((frame-4)*Math.PI/3)*5:0,gait*(worried?2:1));if(fall){c.translate(0,collapse*20);c.scale(1,1-collapse*.75);}
 if(mounted){c.strokeStyle='#513d2d';c.lineWidth=5;for(const [x,k] of [[-22,1],[-12,-1],[13,-1],[23,1]]){c.beginPath();c.moveTo(x,12);c.lineTo(x+gait*k*4,29-gait*k*3);c.stroke();}c.fillStyle='#9c7351';c.beginPath();c.ellipse(0,10,32,15,0,0,7);c.fill();c.beginPath();c.moveTo(15,6);c.lineTo(22,-21);c.lineTo(34,-18);c.lineTo(39,-7);c.lineTo(31,2);c.fill();c.strokeStyle='#44312b';c.lineWidth=4;c.beginPath();c.moveTo(22,-17);c.lineTo(17,5);c.moveTo(-29,7);c.lineTo(-37,22+gait*3);c.stroke();c.fillStyle='#d9c299';c.fillRect(-13,-2,26,11);c.fillStyle='#252826';c.fillRect(31,-13,3,3);c.fillRect(24,-26,4,8);c.fillRect(31,-24,4,7);}
 const size=leader?86:52,top=leader?-59:-39,bottom=mounted?3:leader?27:13;
 // Foot frames alternate the two boot regions without redrawing the source paths.
 c.save();c.beginPath();c.rect(-size/2,top,size,bottom-top-(mounted?12:0));c.clip();c.drawImage(image,-size/2,top,size,size);c.restore();if(!mounted){const bootY=top+size*.78;for(const side of [-1,1]){c.save();c.beginPath();c.rect(side<0?-size/2:0,bootY,size/2,size*.23+5);c.clip();c.drawImage(image,-size/2,top+gait*side*1.5,size,size);c.restore();}}
 if(worried){c.fillStyle='#b5ebfa';for(let i=0;i<2;i++){c.beginPath();c.ellipse(size*.2+i*4,top+size*.3+(frame%2)*3,1.5,3,0,0,7);c.fill();}c.strokeStyle='#f4cf7d';c.lineWidth=2;c.beginPath();c.moveTo(-size*.3,top+7);c.lineTo(-size*.4,top);c.moveTo(-size*.36,top+17);c.lineTo(-size*.48,top+15);c.stroke();}
 return canvas;}
