import {TerrainRenderer} from './terrain-renderer.js';
import {pilotImages} from './pilot-assets.js';
import {translate} from './i18n.js';
import {createCharacterSprite} from './character-sprites.js';
import {CONFIG,villageReward,formation,armyRadius,FACTIONS,visibleCount,displayedFormation} from './config.js';
export class Renderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.camera={x:CONFIG.world/2,y:CONFIG.world/2};this.zoom=1;this.language='en';this.sprites=new Map();this.itemSprites=new Map();this.traceSprites=new Map();this.terrain=new TerrainRenderer();this.resize();}
 resize(){this.w=innerWidth;this.h=innerHeight;const d=Math.min(devicePixelRatio||1,1.5);this.canvas.width=this.w*d;this.canvas.height=this.h*d;this.ctx.setTransform(d,0,0,d,0,0);}
 draw(sim,now,dt=1/60,alpha=1){const c=this.ctx,p=sim.player,px=p.previousX+(p.x-p.previousX)*alpha,py=p.previousY+(p.y-p.previousY)*alpha;const ease=1-Math.exp(-12*dt);this.camera.x+=(px-this.camera.x)*ease;this.camera.y+=(py-this.camera.y)*ease;const targetZoom=Math.min(1,Math.min(this.w,this.h)*.36/(armyRadius(p.units.length)+65));this.zoom+=(targetZoom-this.zoom)*(1-Math.exp(-4*dt));c.fillStyle='#29463b';c.fillRect(0,0,this.w,this.h);c.save();c.translate(this.w/2,this.h/2);c.scale(this.zoom,this.zoom);c.translate(-this.camera.x,-this.camera.y);
 const left=this.camera.x-this.w/2/this.zoom-100,top=this.camera.y-this.h/2/this.zoom-100,right=this.camera.x+this.w/2/this.zoom+100,bottom=this.camera.y+this.h/2/this.zoom+100;if(sim.map)this.terrain.draw(c,sim.map,{left,top,right,bottom},this.zoom);
 c.strokeStyle='#c5a963';c.lineWidth=8;c.strokeRect(0,0,CONFIG.world,CONFIG.world);
 for(const trace of sim.traces){if(trace.x>=left&&trace.x<=right&&trace.y>=top&&trace.y<=bottom)this.trace(trace);}
 for(const r of sim.resources){if(r.x+(r.kind==='village'?400:0)<left||r.x-(r.kind==='village'?400:0)>right||r.y+(r.kind==='village'?400:0)<top||r.y-(r.kind==='village'?400:0)>bottom)continue;this.item({...r,reward:r.kind==='village'?villageReward((r.assailant||p).units.length)*((r.assailant||p).growthUntil>sim.time?2:1):0},now);}
 const champion=sim.rank().find(h=>h.alive);for(const h of sim.hordes){const hx=h.previousX+(h.x-h.previousX)*alpha,hy=h.previousY+(h.y-h.previousY)*alpha,r=armyRadius(h.units.length);if(!h.alive||hx+r<left||hx-r>right||hy+r<top||hy-r>bottom)continue;c.globalAlpha=.055;c.fillStyle=h.color;c.beginPath();c.arc(hx,hy,r,0,Math.PI*2);c.fill();c.globalAlpha=.5;c.strokeStyle=h.color;c.lineWidth=(h===p?2:1)/this.zoom;c.setLineDash([4/this.zoom,8/this.zoom]);c.beginPath();c.arc(hx,hy,r,0,Math.PI*2);c.stroke();c.globalAlpha=1;c.setLineDash([]);if(h.speedUntil>sim.time){c.strokeStyle='#9cdff0';c.beginPath();c.arc(hx,hy,r+6,now*2,now*2+4);c.stroke();}for(let i=visibleCount(h.units.length)-1;i>=1;i--){const f=displayedFormation(i,h.units.length);const x=hx+f.x,y=hy+f.y;if(x<left||x>right||y<top||y>bottom)continue;this.unit(x,y,h,i,now,sim.time);}this.unit(hx,hy,h,0,now,sim.time);c.textAlign='center';c.font='bold 12px system-ui';c.fillStyle=h===p?'#ffe4a0':'#e7eee4';const first=champion===h;c.fillText((first?'♛ '+translate(this.language,'title_'+h.faction)+' ':'')+(h===sim.player?translate(this.language,'you'):h.name)+' · '+h.units.length,hx,hy-r-15);c.font='9px system-ui';c.fillStyle='#aebdb4';c.fillText(translate(this.language,'faction_'+h.faction),hx,hy+r+20);const hp=h.units[0]?.hp||0;c.fillStyle='#102321';c.fillRect(hx-20,hy-r-10,40,3);c.fillStyle=h.color;c.fillRect(hx-20,hy-r-10,40*hp/8,3);}
 for(const e of sim.effects){c.globalAlpha=Math.min(1,e.life*2);c.font='bold 15px system-ui';c.fillStyle=e.color;c.textAlign='center';if(e.kind==='notice'){/* Notifications render once in the screen-space HUD. */}else if(e.kind==='pickup'){c.save();c.translate(e.x,e.y);c.globalAlpha=e.life/.35;c.scale(.65+e.life,.65+e.life);this.paintItem({x:0,y:0,kind:e.itemKind,appearance:e.appearance},0);c.restore();}else if(e.kind==='transfer'){c.save();c.globalAlpha=e.life/.45;c.strokeStyle='#a3dfce';c.lineWidth=2;c.setLineDash([5,9]);c.lineDashOffset=-e.life*80;c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.to.x,e.to.y);c.stroke();c.restore();}else if(e.kind==='kingFall'){const progress=1-e.life/1.4,sprite=this.sprite(e.faction,true,e.mounted,16+Math.min(3,Math.floor(progress*4)),e.facing);c.globalAlpha=1;c.drawImage(sprite,e.x-55,e.y-68,110,136);}else if(e.kind==='fall'){this.paintTrace({x:e.x,y:e.y,kind:'bones',angle:0});}else if(e.kind==='slash'){c.save();c.translate(e.x,e.y);c.rotate(e.angle);c.strokeStyle=e.color;c.lineWidth=2+e.life*8;c.beginPath();c.arc(0,0,14+(1-e.life/.3)*25,-1.3,1.3);c.stroke();c.fillStyle='#fff2cd';for(let i=0;i<4;i++){c.fillRect(Math.cos(i*1.7)*25*(1-e.life/.3),Math.sin(i*1.7)*25*(1-e.life/.3),3,3);}c.restore();}else c.fillText(e.kind==='growth'?'':this.effectText(e.text,sim.player.name),e.x,e.y-(1-e.life)*20);}c.globalAlpha=1;c.restore();this.minimap(sim);}
 // Build small sprite frames once; gameplay frames only transform and blit bitmaps.
 effectText(text,playerName){if(text==='SPEED +45%')return translate(this.language,'speed')+' +45%';if(text==='CONQUEST · GROWTH ×2')return translate(this.language,'conquest')+' · '+translate(this.language,'growth')+' ×2';if(text?.startsWith('VILLAGE CONQUERED'))return translate(this.language,'villageConquered')+' +'+text.split('+').pop();if(text?.endsWith(' cayó')){const name=text.slice(0,-5);return translate(this.language,'fell',{name:name===playerName?translate(this.language,'you'):name});}return text;}
 leaderSprite(faction,mounted,frame,facing=1){return this.sprite(faction,true,mounted,frame,facing);}
 sprite(faction,leader,mounted,frame,facing=1){const key=[faction,leader,mounted,frame,facing].join(':');if(!this.sprites.has(key))this.sprites.set(key,createCharacterSprite(faction,leader,mounted,frame,facing));return this.sprites.get(key);}
 unit(x,y,h,i,t,gameTime){const attack=h.attackUntil>gameTime,frame=i===0&&h.desperate?12+Math.floor(t*15)%4:i===0&&!attack&&!h.moving?8+Math.floor(t*4)%4:attack?4+Math.floor(t*12+i%2)%4:h.moving?1+Math.floor(t*9+i%3)%3:0;const mounted=!!h.mount&&h.speedUntil>gameTime,sprite=this.sprite(h.faction,i===0,mounted,frame,h.facing||1),c=this.ctx;c.save();c.translate(x,y);const displayScale=Math.max(1,(i===0?.65:.45)/this.zoom);c.scale(displayScale,displayScale);const bob=h.moving?Math.sin(t*10+i)*.7:0;if(i===0){c.drawImage(sprite,-55,-68+bob,110,136);}else c.drawImage(sprite,-32,-40+bob,64,80);if(h.flash>0&&i%5===0){c.fillStyle='#ffe6bf';c.globalAlpha=h.flash/.14*.3;c.fillRect(-5,-10,10,14);}c.restore();}
 item(r,t){if(r.kind==='loot'&&r.owner)return;const animated=r.kind==='village'||r.kind==='noble';if(animated){this.paintItem(r,t);return;}let sprite=this.itemSprites.get(this.language+':'+r.kind+':'+r.appearance);if(!sprite){sprite=document.createElement('canvas');sprite.width=80;sprite.height=100;const old=this.ctx;this.ctx=sprite.getContext('2d');this.paintItem({...r,x:40,y:40},0);this.ctx=old;this.itemSprites.set(this.language+':'+r.kind+':'+r.appearance,sprite);}this.ctx.drawImage(sprite,r.x-40,r.y-40);}
 trace(r){const key=r.kind+':'+r.color;let sprite=this.traceSprites.get(key);if(!sprite){sprite=document.createElement('canvas');sprite.width=64;sprite.height=64;const old=this.ctx;this.ctx=sprite.getContext('2d');this.paintTrace({...r,x:32,y:32,angle:0});this.ctx=old;this.traceSprites.set(key,sprite);}const c=this.ctx;c.save();c.translate(r.x,r.y);c.rotate(r.angle);c.drawImage(sprite,-32,-32);c.restore();}
 paintItem(r,t){const c=this.ctx;c.save();c.translate(r.x,r.y);if(r.kind==='village')c.scale(CONFIG.villageScale,CONFIG.villageScale);const special=['horse','wagon','village','noble'].includes(r.kind);c.fillStyle=special?'#142a28aa':'#152d2655';c.beginPath();c.ellipse(0,6,special?25:10,special?12:6,0,0,7);c.fill();
 if(r.kind==='loot'){if(!r.owner){c.fillStyle='#b5d8c3';c.fillRect(-3,-4,6,8);}} else if(r.kind==='village'){c.strokeStyle='#edcf87';c.lineWidth=2;c.beginPath();c.arc(0,0,36,0,7);c.stroke();if(pilotImages.town)c.drawImage(pilotImages.town,-34,-34,68,68);else for(const [x,y] of [[-15,5],[13,8],[0,-12]]){c.fillStyle='#d1b890';c.fillRect(x-9,y-7,18,16);c.fillStyle='#9c5640';c.beginPath();c.moveTo(x-12,y-7);c.lineTo(x,y-20);c.lineTo(x+12,y-7);c.fill();c.fillStyle='#47372b';c.fillRect(x-3,y+1,6,8);}c.fillStyle='#ffe1a0';c.font='bold 3px system-ui';c.textAlign='center';c.fillText(translate(this.language,'assault')+' · +'+(r.reward??CONFIG.villageReward),0,51);c.fillStyle='#13231f';c.fillRect(-36,58,72,6);c.fillStyle='#eec569';c.fillRect(-36,58,72*(r.progress||0)/CONFIG.villageDuration,6);if(r.progress>0){c.fillStyle='#ff9953';for(let i=0;i<3;i++){c.beginPath();c.ellipse(-15+i*15,-18-Math.sin(t*10+i)*5,4,7,0,0,7);c.fill();}c.fillStyle='#eec569';c.fillText(Math.ceil(CONFIG.villageDuration-r.progress)+'s',0,77);}}
 else if(r.kind==='horse'||r.kind==='noble'){c.fillStyle=r.kind==='noble'?'#ddd2b4':'#9a7151';c.beginPath();c.ellipse(0,0,17,9,0,0,7);c.fill();c.fillRect(-12,5,4,11);c.fillRect(7,5,4,11);c.beginPath();c.moveTo(8,-4);c.lineTo(13,-19);c.lineTo(21,-14);c.lineTo(20,-5);c.fill();c.fillStyle='#3c302b';c.fillRect(-19,-3,5,12);c.fillRect(10,-19,4,10);c.fillStyle='#503a29';c.fillRect(-5,-8,10,8);if(r.kind==='noble'){c.fillStyle='#7953a3';c.fillRect(-5,-18,10,12);c.fillStyle='#d5b798';c.beginPath();c.arc(0,-21,5,0,7);c.fill();c.fillStyle='#eec569';c.fillRect(-6,-28,12,5);c.fillRect(-6,-32,3,5);c.fillRect(-1,-32,3,5);c.fillRect(3,-32,3,5);}c.strokeStyle=r.kind==='noble'?'#ddbdff':'#9cdff0';c.lineWidth=2;c.beginPath();c.arc(0,0,29,0,7);c.stroke();c.textAlign='center';c.font='bold 10px system-ui';c.fillStyle=c.strokeStyle;c.fillText(r.kind==='noble'?translate(this.language,'noble')+' +8':translate(this.language,'speed'),0,42);}
 else if(r.kind==='wagon'){c.strokeStyle='#9cdff0';c.lineWidth=2;c.beginPath();c.arc(0,0,26,0,7);c.stroke();c.fillStyle='#8c603c';c.fillRect(-16,-10,32,20);c.fillStyle='#d6c2a2';c.beginPath();c.ellipse(0,-8,14,10,0,Math.PI,Math.PI*2);c.fill();c.fillRect(-14,-8,28,6);for(const x of [-11,11]){c.fillStyle='#312a25';c.beginPath();c.arc(x,10,6,0,7);c.fill();c.fillStyle='#b8a282';c.beginPath();c.arc(x,10,2,0,7);c.fill();}c.fillStyle='#9cdff0';c.textAlign='center';c.font='bold 10px system-ui';c.fillText(translate(this.language,'speed'),0,40);}
 else if(r.kind==='recruit'){c.strokeStyle='#9ce6cf';c.lineWidth=1.5;c.beginPath();c.arc(0,3,20,0,7);c.stroke();const bandit=r.appearance==='bandit';c.fillStyle='#92d4bc';c.globalAlpha=.2;c.beginPath();c.ellipse(0,9,15,7,0,0,7);c.fill();c.globalAlpha=1;c.fillStyle=bandit?'#67454e':'#6b8d70';c.beginPath();c.moveTo(-7,-3);c.lineTo(-10,11);c.lineTo(10,11);c.lineTo(7,-3);c.fill();c.fillStyle='#d9b18d';c.beginPath();c.arc(0,-6,5,0,7);c.fill();c.fillStyle=bandit?'#3e303d':'#54745d';c.beginPath();c.arc(0,-8,7,Math.PI,Math.PI*2);c.fill();if(bandit){c.fillRect(-5,-6,10,3);}c.strokeStyle='#b6dbbe';c.lineWidth=2;c.beginPath();c.moveTo(11,-9);c.lineTo(11,15);c.stroke();c.fillStyle='#d4eada';c.font='bold 9px system-ui';c.textAlign='center';c.fillText('+2',0,24);}
 else if(r.kind==='supplies'){c.fillStyle='#e9c58a';c.strokeStyle='#9b774a';c.lineWidth=2;c.beginPath();c.roundRect(-12,-4,24,18,4);c.fill();c.stroke();c.fillStyle='#e4b768';c.beginPath();c.ellipse(-5,-6,5,9,-.5,0,7);c.fill();c.strokeStyle='#93643b';c.lineWidth=1;c.beginPath();c.moveTo(-8,-10);c.lineTo(-3,-8);c.moveTo(-10,-5);c.lineTo(-5,-3);c.stroke();c.fillStyle='#b76855';c.beginPath();c.arc(3,-3,5,0,7);c.fill();c.fillStyle='#a4ba72';c.fillRect(2,-10,3,4);c.fillStyle='#afc5c2';c.fillRect(7,-12,5,14);c.fillStyle='#715e48';c.fillRect(8,-15,3,4);c.strokeStyle='#ffe4b3';c.lineWidth=1.5;c.beginPath();c.arc(0,2,21,0,7);c.stroke();}else{c.fillStyle='#a3dfce';c.font='bold 14px system-ui';c.textAlign='center';c.fillText('⚑',0,5);}c.restore();}

 paintUnit(x,y,h,i,t,gameTime){const c=this.ctx,f=FACTIONS[h.faction],walk=h.moving?Math.sin(t*10+i)*1.5:0;c.save();c.translate(x,y);c.scale(i?1:1.3,i?1:1.3);c.fillStyle='#0b1e1c77';c.beginPath();c.ellipse(0,9,11,6,0,0,7);c.fill();if(h.mount&&h.speedUntil>gameTime){this.horse(t,i);c.translate(0,-4);}c.lineWidth=1.5;c.strokeStyle='#192325';
 // Boots, layered cape, shoulder armor and tunic form a readable silhouette.
 c.fillStyle='#292b2b';c.fillRect(-6,7+walk,4,6);c.fillRect(2,7-walk,4,6);c.fillStyle=f.cloth;c.beginPath();c.moveTo(-7,-4);c.lineTo(-9,10);c.lineTo(9,10);c.lineTo(7,-4);c.closePath();c.fill();c.stroke();c.fillStyle=h.flash?'#fff4d2':f.helmet;c.beginPath();c.ellipse(0,1,6,8,0,0,7);c.fill();c.stroke();c.fillStyle=h.color;c.fillRect(-5,0,10,3);c.fillStyle='#b5afa0';c.fillRect(-8,-4,4,5);c.fillRect(4,-4,4,5);c.fillStyle=h.faction==='undead'?'#e5e1bf':'#dab394';c.beginPath();c.arc(0,-8,5,0,7);c.fill();c.stroke();c.fillStyle=f.helmet;c.beginPath();c.ellipse(0,-11,6,4,0,Math.PI,Math.PI*2);c.fill();
 if(h.faction==='vikings'){c.fillStyle='#876449';c.fillRect(-4,-7,8,4);c.strokeStyle='#dfd3ad';c.beginPath();c.moveTo(-5,-12);c.lineTo(-9,-17);c.lineTo(-11,-14);c.moveTo(5,-12);c.lineTo(9,-17);c.lineTo(11,-14);c.stroke();}
 if(h.faction==='romans'||h.faction==='spartans'){c.fillStyle='#a33832';c.fillRect(-2,-19,4,9);c.fillStyle=f.helmet;c.fillRect(-5,-10,2,6);c.fillRect(3,-10,2,6);}
 if(h.faction==='samurai'){c.fillStyle=f.helmet;c.fillRect(-8,-12,16,4);c.strokeStyle='#e9c16d';c.beginPath();c.moveTo(-5,-13);c.lineTo(-7,-20);c.lineTo(0,-16);c.lineTo(7,-20);c.lineTo(5,-13);c.stroke();for(let yy=3;yy<10;yy+=3){c.strokeStyle='#af7389';c.beginPath();c.moveTo(-6,yy);c.lineTo(6,yy);c.stroke();}}
 if(h.faction==='mongols'){c.fillStyle='#6b4434';c.beginPath();c.moveTo(-6,-11);c.lineTo(0,-20);c.lineTo(6,-11);c.fill();c.fillStyle='#c2b8a3';c.fillRect(-6,-12,12,3);}
 if(h.faction==='undead'){c.fillStyle='#232632';c.fillRect(-4,-9,3,3);c.fillRect(1,-9,3,3);c.fillRect(-2,-4,4,2);c.strokeStyle='#e5e1bf';c.beginPath();c.moveTo(-3,3);c.lineTo(3,3);c.moveTo(-3,6);c.lineTo(3,6);c.stroke();}
 c.save();c.translate(9,0);if(h.attackUntil>gameTime)c.rotate(Math.sin(t*18+i)*.8);c.translate(-9,0);c.strokeStyle='#443326';c.lineWidth=2;c.beginPath();c.moveTo(9,9);c.lineTo(9,-13);c.stroke();c.fillStyle='#d1dce0';if(h.faction==='vikings'){c.beginPath();c.moveTo(9,-12);c.lineTo(16,-14);c.lineTo(15,-6);c.lineTo(9,-8);c.fill();}else if(h.faction==='mongols'){c.strokeStyle='#ddb97c';c.beginPath();c.arc(9,0,11,-1.3,1.3);c.stroke();c.beginPath();c.moveTo(12,-10);c.lineTo(12,10);c.stroke();}else{c.beginPath();c.moveTo(8,-9);c.lineTo(9,-23);c.lineTo(11,-9);c.fill();}
 c.restore();c.fillStyle=f.shield;c.strokeStyle='#292c29';c.lineWidth=1.5;c.beginPath();if(h.faction==='romans'){c.rect(-16,-6,9,17);}else{c.ellipse(-10,2,6,8,0,0,7);}c.fill();c.stroke();c.fillStyle='#efe0b0';c.font='bold 8px system-ui';c.textAlign='center';c.fillText(h.faction==='spartans'?'Λ':h.faction==='romans'?'I':'•',-11,5);if(!i){c.fillStyle='#eec569';c.beginPath();c.moveTo(-5,-15);c.lineTo(-6,-21);c.lineTo(-2,-18);c.lineTo(0,-23);c.lineTo(2,-18);c.lineTo(6,-21);c.lineTo(5,-15);c.fill();}c.restore();}
 horse(t,i){const c=this.ctx,gait=Math.sin(t*13+i)*4;c.fillStyle=i%3?'#99704d':'#c6b897';c.strokeStyle='#332c25';c.lineWidth=1.5;c.beginPath();c.ellipse(0,5,11,19,0,0,7);c.fill();c.stroke();c.fillRect(-12,5+gait,4,12);c.fillRect(8,5-gait,4,12);c.fillRect(-10,-8-gait,4,10);c.fillRect(6,-8+gait,4,10);c.beginPath();c.ellipse(0,-19,6,11,0,0,7);c.fill();c.stroke();c.fillStyle='#342b25';c.fillRect(-2,-23,4,21);c.fillRect(-2,22,4,13);c.fillStyle='#5d3e2c';c.fillRect(-9,-2,18,10);c.strokeStyle='#ddc79a';c.beginPath();c.moveTo(-5,-19);c.lineTo(-8,2);c.moveTo(5,-19);c.lineTo(8,2);c.stroke();}
 paintTrace(r){const c=this.ctx;c.save();c.translate(r.x,r.y);c.rotate(r.angle);c.globalAlpha=.5;if(r.kind==='crown'){c.fillStyle='#bca468';c.beginPath();c.moveTo(-10,5);c.lineTo(-12,-7);c.lineTo(-5,-2);c.lineTo(0,-11);c.lineTo(5,-2);c.lineTo(12,-7);c.lineTo(10,5);c.fill();c.strokeStyle='#6c5140';c.beginPath();c.moveTo(-3,-7);c.lineTo(2,5);c.stroke();}else if(r.kind==='blood'){c.fillStyle='#873d36';for(let i=0;i<4;i++){c.beginPath();c.ellipse(i*4-6,Math.sin(i*3)*6,5+i*2,4+i,0,0,7);c.fill();}}else if(r.kind==='bones'){c.strokeStyle='#889ba1';c.lineWidth=3;c.beginPath();c.moveTo(-7,-4);c.lineTo(7,4);c.moveTo(-6,5);c.lineTo(6,-5);c.stroke();c.fillStyle='#9aadb1';c.beginPath();c.arc(0,-8,4,0,7);c.fill();c.fillStyle='#3d4237';c.fillRect(-2,-9,1.5,2);c.fillRect(1,-9,1.5,2);}else if(r.kind==='shield'){c.fillStyle=r.color;c.strokeStyle='#3c382b';c.beginPath();c.ellipse(0,0,7,9,0,0,7);c.fill();c.stroke();c.fillStyle='#bcaf8a';c.fillRect(-1,-7,2,14);}else if(r.kind==='arms'){c.strokeStyle='#c1cbd0';c.lineWidth=2;c.beginPath();c.moveTo(-9,0);c.lineTo(9,0);c.stroke();c.strokeStyle='#795d39';c.beginPath();c.moveTo(-6,-4);c.lineTo(-6,4);c.stroke();}else{c.fillStyle='#6c5941';c.fillRect(-20,-15,40,30);c.fillStyle='#272e27';c.fillRect(-13,-9,26,18);}c.restore();}
 minimap(sim){const c=this.ctx,s=this.w<600?90:126,x=this.w-s-24,y=this.h-s-25;c.fillStyle='#102321d9';c.fillRect(x,y,s,s);if(sim.map)this.terrain.minimap(c,sim.map,x,y,s);c.strokeStyle='#78917b66';c.strokeRect(x,y,s,s);for(const r of sim.resources){if(r.kind==='village'||r.kind==='noble'){c.fillStyle=r.kind==='village'?'#eec569':'#dbc0ff';c.fillRect(x+r.x/CONFIG.world*s-2,y+r.y/CONFIG.world*s-2,4,4);}}for(const h of sim.hordes){if(!h.alive)continue;c.fillStyle=h===sim.player?'#ffe1a0':'#cb8979';c.beginPath();c.arc(x+h.x/CONFIG.world*s,y+h.y/CONFIG.world*s,h===sim.player?3:2,0,7);c.fill();}c.strokeStyle='#c3d3bb44';c.strokeRect(x+(this.camera.x-this.w/2/this.zoom)/CONFIG.world*s,y+(this.camera.y-this.h/2/this.zoom)/CONFIG.world*s,this.w/this.zoom/CONFIG.world*s,this.h/this.zoom/CONFIG.world*s);}
}
