import {PlayerLifecycle} from './player-lifecycle.js';
import {updateRun} from './run-stats.js';
import {generateWorld,sampleLand} from './world.js';
import {facingForVector} from './character-sprites.js';
import {Army} from './army.js';
import {DIFFICULTIES} from './progression.js';
import {ResourceGrid} from './spatial.js';
import {CONFIG,villageReward,FACTIONS,UNIT_TYPES,clamp,distance,speed,armyRadius,formation,visibleCount,displayedFormation} from './config.js';
export class Simulation{
 constructor(random=Math.random,faction='vikings',difficulty='hard',options={}){this.difficulty=DIFFICULTIES[difficulty]?difficulty:'hard';this.rules=DIFFICULTIES[this.difficulty];this.grid=new ResourceGrid();this.gridTimer=0;this.indexedResources=null;this.random=random;this.map=generateWorld(Math.floor(random()*4294967296));this.time=0;this.ended=false;this.victory=false;this.lifecycle=new PlayerLifecycle(this,options);this.effects=[];this.fallen=[];this.audioEvents=[];this.traces=[];this.resources=[];this.hordes=[];this.kills=0;this.attackTimer=0;this.respawnTimer=0;this.eventTimer=50+random()*25;this.player=this.makeHorde('Tú',CONFIG.world/2,CONFIG.world/2,4,'#eec569',faction);this.hordes.push(this.player);const names=['Ragnar','Cassius','Akira','Leonidas','Temujin','Mordred','Astrid','Aurelia','Yuki','Lysandra','Batu','Nyx'];names.slice(0,CONFIG.bots).forEach((n,i)=>{let position;for(let attempt=0;attempt<30;attempt++){position=sampleLand(this.map,this.random,{margin:150});if(Math.hypot(position.x-this.player.x,position.y-this.player.y)>750&&this.hordes.every(h=>distance(h,position)>320))break;}this.hordes.push(this.makeHorde(n,position.x,position.y,this.rules.botStart+Math.floor(this.random()*3),`hsl(${i*29+5} 45% 65%)`,Object.keys(FACTIONS)[i%6]));});for(let i=0;i<CONFIG.resources;i++)this.spawnResource();for(let i=0;i<50;i++){const a=this.random()*Math.PI*2,r=85+Math.sqrt(this.random())*450,position=sampleLand(this.map,this.random,{center:{x:this.player.x+Math.cos(a)*r,y:this.player.y+Math.sin(a)*r},radius:25});this.spawnResource(position.x,position.y,'recruit');}for(let i=0;i<6;i++)this.spawnResource(undefined,undefined,i%2?'wagon':'horse');this.spawnEvent('village');this.spawnEvent('noble');for(const h of this.hordes)this.lifecycle.register(h);this.player.protectedUntil=this.rules.protection;this.peak=4;this.grid.rebuild(this.resources);}
 makeHorde(name,x,y,count,color,faction='vikings'){return{name,x,y,previousX:x,previousY:y,color,faction:FACTIONS[faction]?faction:'vikings',units:new Army(count),score:0,alive:true,angle:0,pickup:0,think:0,target:null,flash:0,speedUntil:0,growthUntil:0,fedUntil:0,foodCollected:0,conquests:0,mount:null,attackUntil:0,opponents:[],siege:null,moving:false,recruitPulse:0,peakCount:count,lastLoss:-100,desperate:false,visualAngle:0,facing:1};}
 spawnResource(x,y,kind=this.random()<.65?'recruit':'supplies',extra={}){if(x===undefined||y===undefined){const clustered=this.random()<.58,center=clustered?this.map.clearings[Math.floor(this.random()*this.map.clearings.length)]:null,position=sampleLand(this.map,this.random,{center,radius:center?center.radius+120:0});x??=position.x;y??=position.y;}const r={x:clamp(x,35,CONFIG.world-35),y:clamp(y,35,CONFIG.world-35),kind,appearance:kind==='supplies'?'provisions':kind==='recruit'?(this.random()<.5?'wanderer':'bandit'):kind,...extra};this.resources.push(r);this.grid.add(r);return r;}
 spawnEvent(kind=this.random()<.6?'village':'noble'){const sites=this.map.clearings.filter(c=>distance(c,this.player)>550&&this.resources.every(r=>r.kind!=='village'||distance(c,r)>500)),site=sites[Math.floor(this.random()*sites.length)],position=site?sampleLand(this.map,this.random,{center:site,radius:35,margin:280,waterMargin:kind==='village'?205:30}):sampleLand(this.map,this.random,{margin:280,waterMargin:205});return this.spawnResource(position.x,position.y,kind,{expires:this.time+90,angle:this.random()*6.28,progress:0,assailant:null});}
 rank(){return this.hordes.filter(h=>h.alive).sort((a,b)=>b.units.length-a.units.length||a.id-b.id);}
 recruit(h,value=1){if(!h.alive)return;const added=value*(h.growthUntil>this.time?2:1);h.units.add(added);h.recruitPulse=.18;if(h.run)updateRun(h,this.time);const recent=this.effects.find(e=>e.kind==='growth'&&e.horde===h&&e.life>.3);if(recent){recent.value+=added;recent.text='+'+recent.value;recent.life=.65;recent.x=h.x;recent.y=h.y;}else this.effects.push({kind:'growth',horde:h,value:added,x:h.x,y:h.y,text:added?'+'+added:'HEAL',color:h.color,life:.65});}
 notice(h,key,data={},color='#a3dfce'){if(h!==this.player)return;const recent=this.effects.find(e=>e.kind==='notice'&&e.key===key&&e.data.name===data.name&&e.life>.2);if(recent){recent.data.count=(recent.data.count||0)+(data.count||0);recent.life=1.1;recent.x=h.x;recent.y=h.y-75;}else this.effects.push({kind:'notice',key,data,x:h.x,y:h.y-75,color,life:1.1});}
 collect(h,r){if(!h.alive)return;if(r.kind==='horse'||r.kind==='wagon'){h.speedUntil=this.time+CONFIG.speedDuration;h.mount=r.kind;this.sound('horse',h);this.effects.push({x:h.x,y:h.y,text:'SPEED +45%',color:'#9cdff0',life:1.5});return;}if(r.kind==='supplies'){h.foodCollected++;h.score+=5;h.fedUntil=this.time+CONFIG.foodDuration;const leader=h.units[0],front=h.units.at(-1);if(leader)leader.hp=Math.min(8,leader.hp+4);if(front&&front!==leader)front.hp=Math.min(3,front.hp+2);this.notice(h,'foodAcquired',{},'#eac98f');this.sound('food',h);if(h===this.player)this.effects.push({kind:'pickup',itemKind:'supplies',appearance:'provisions',x:r.x??h.x,y:r.y??h.y,life:.35,color:'#eac98f'});return;}if(r.kind==='village'&&!r.captured)return;const value=r.kind==='village'?(r.value??villageReward(h.units.length)):r.kind==='noble'?8:r.value||(r.kind==='recruit'?2:1);h.score+=r.kind==='supplies'?5:value*10;this.recruit(h,value);if(r.kind==='loot'){this.notice(h,'absorbed',{count:value*(h.growthUntil>this.time?2:1),name:r.source||'—'});if(h===this.player)this.effects.push({kind:'transfer',x:r.x,y:r.y,to:h,life:.45,color:'#a3dfce'});}else if(r.kind==='recruit'||r.kind==='noble'){this.notice(h,'recruited',{count:value*(h.growthUntil>this.time?2:1)});if(h===this.player)this.effects.push({kind:'pickup',itemKind:'recruit',appearance:r.appearance,x:r.x??h.x,y:r.y??h.y,life:.35,color:'#a3dfce'});}this.sound(r.kind==='village'?'village':'pickup',h);}
 ai(h,dt){h.think-=dt;if(h.think<=0){h.think=(this.difficulty==='easy'?.65:.3)+this.random()*.4;const threats=this.hordes.filter(o=>o!==h&&o.alive&&o.units.length>h.units.length*1.2&&distance(o,h)<armyRadius(o.units.length)+armyRadius(h.units.length)+160);if(threats.length){const o=threats.sort((a,b)=>distance(a,h)-distance(b,h))[0];h.target={x:h.x+(h.x-o.x)*3,y:h.y+(h.y-o.y)*3};}else{const prey=this.hordes.find(o=>o!==h&&o.alive&&o.units.length<h.units.length*.7&&distance(o,h)<420&&!(o===this.player&&(!this.rules.huntPlayer||this.time<this.player.protectedUntil)));h.target=prey||this.nearestResource(h);}}return h.target?{x:h.target.x-h.x,y:h.target.y-h.y}:{x:0,y:0};}
 update(dt,input={x:0,y:0}){dt=clamp(dt,0,.05);this.time+=dt;this.effects=this.effects.filter(e=>(e.life-=dt)>0).slice(-100);for(const h of this.hordes){h.previousX=h.x;h.previousY=h.y;h.opponents=[];h.siege=null;if(h.speedUntil<=this.time)h.mount=null;}
 // Casualties fade locally and recruit directly; no flying orb objects.
 for(let i=this.resources.length-1;i>=0;i--){const r=this.resources[i];if(r.expires&&r.expires<=this.time){r.removed=true;this.resources.splice(i,1);continue;}if(r.kind==='noble'){r.x=clamp(r.x+Math.cos(r.angle)*32*dt,40,CONFIG.world-40);r.y=clamp(r.y+Math.sin(r.angle)*32*dt,40,CONFIG.world-40);if(r.x===40||r.x===CONFIG.world-40||r.y===40||r.y===CONFIG.world-40)r.angle+=Math.PI;}if(!r.owner)continue;if(!r.owner.alive){r.owner=null;continue;}if(this.time<r.ready)continue;this.collect(r.owner,r);r.removed=true;this.resources.splice(i,1);}
 this.gridTimer-=dt;if(this.gridTimer<=0||this.indexedResources!==this.resources){this.grid.rebuild(this.resources);this.indexedResources=this.resources;this.gridTimer=.2;}
 for(const h of this.hordes){if(!h.alive)continue;h.flash=Math.max(0,h.flash-dt);h.recruitPulse=Math.max(0,h.recruitPulse-dt);h.pickup=Math.max(0,h.pickup-dt);let v=h===this.player?input:this.ai(h,dt),len=Math.hypot(v.x,v.y);h.moving=len>5;h.peakCount=Math.max(h.peakCount,h.units.length);h.desperate=h.moving&&h.units.length<=Math.max(4,h.peakCount*.2)&&this.time-h.lastLoss<8;if(h.moving)h.facing=facingForVector(v.x,v.y,h.facing);if(len>5){const step=Math.min(len,speed(h.units.length)*(h.speedUntil>this.time?1.45:1)*(h===this.player?1:this.rules.botSpeed)*dt);h.x=clamp(h.x+v.x/len*step,25,CONFIG.world-25);h.y=clamp(h.y+v.y/len*step,25,CONFIG.world-25);h.angle=Math.atan2(v.y,v.x);}if(h.pickup<=0){const reach=armyRadius(h.units.length)+24,dx=h.x-h.previousX,dy=h.y-h.previousY,length2=dx*dx+dy*dy,candidates=this.grid.query((h.x+h.previousX)/2,(h.y+h.previousY)/2,reach+Math.sqrt(length2)/2).filter(r=>{if(r.owner||r.kind==='village'||r.removed)return false;const t=length2?clamp(((r.x-h.previousX)*dx+(r.y-h.previousY)*dy)/length2,0,1):0;return Math.hypot(r.x-h.previousX-dx*t,r.y-h.previousY-dy*t)<reach;}).sort((a,b)=>distance(a,h)-distance(b,h));const limit=h===this.player?Math.min(32,6+Math.floor(Math.sqrt(h.units.length)/8)):1;for(const r of candidates.slice(0,limit)){r.removed=true;this.collect(h,r);}if(candidates.length)h.pickup=h===this.player?.075:this.rules.botPickup;}}
 let write=0;for(const resource of this.resources)if(!resource.removed)this.resources[write++]=resource;this.resources.length=write;

 this.updateVillages(dt);this.updateContacts();this.attackTimer-=dt;if(this.attackTimer<=0){this.attackTimer=CONFIG.attackInterval;for(let i=0;i<this.hordes.length;i++)for(let j=i+1;j<this.hordes.length;j++){const a=this.hordes[i],b=this.hordes[j];if(!a.alive||!b.alive||this.time<a.protectedUntil||this.time<b.protectedUntil)continue;const reach=armyRadius(a.units.length)+armyRadius(b.units.length),overlap=reach-distance(a,b);if(overlap>0)this.battle(a,b,clamp(overlap/Math.min(armyRadius(a.units.length),armyRadius(b.units.length)),.15,1));}}
 this.updateContactsAfterBattle();this.respawnTimer+=dt;if(this.respawnTimer>1){this.respawnTimer=0;const ordinary=this.resources.filter(r=>r.kind==='recruit'||r.kind==='supplies').length;for(let i=0;i<8&&ordinary+i<CONFIG.resources;i++)this.spawnResource();if(this.resources.filter(r=>r.kind==='horse'||r.kind==='wagon').length<6&&this.random()<.2)this.spawnResource(undefined,undefined,this.random()<.5?'horse':'wagon');}this.eventTimer-=dt;if(this.eventTimer<=0){this.eventTimer=55+this.random()*25;if(this.resources.filter(r=>r.kind==='village'||r.kind==='noble').length<4)this.spawnEvent();}this.lifecycle.update();this.peak=this.player.records.largestArmy;this.kills=this.player.run.kills;
 }
 sound(kind,h=this.player){if(h===this.player){this.audioEvents.push(kind);if(this.audioEvents.length>16)this.audioEvents.shift();}}
 nearestResource(h){const nearby=this.grid.query(h.x,h.y,900);let best=null,bestD=Infinity;for(const r of nearby.length?nearby:this.resources){if(r.owner||r.kind==='loot'||r.removed)continue;const d=(h.x-r.x)**2+(h.y-r.y)**2;if(d<bestD){best=r;bestD=d;}}return best;}
 updateContactsAfterBattle(){for(const h of this.hordes)h.opponents=!h.alive?[]:h.opponents.filter(name=>this.hordes.some(o=>o.name===name&&o.alive));}
 updateContacts(){for(let i=0;i<this.hordes.length;i++)for(let j=i+1;j<this.hordes.length;j++){const a=this.hordes[i],b=this.hordes[j];if(a.alive&&b.alive&&!(this.time<a.protectedUntil||this.time<b.protectedUntil)&&distance(a,b)<armyRadius(a.units.length)+armyRadius(b.units.length)){a.opponents.push(b.name);b.opponents.push(a.name);}}}
 updateVillages(dt){for(let i=this.resources.length-1;i>=0;i--){const v=this.resources[i];if(v.kind!=='village')continue;const nearby=this.hordes.filter(h=>h.alive&&distance(h,v)<armyRadius(h.units.length)+CONFIG.villageRadius);if(nearby.length!==1){if(!nearby.length)v.progress=Math.max(0,(v.progress||0)-dt*.5);for(const h of nearby)h.siege={village:v,contested:true};continue;}const h=nearby[0];if(v.assailant!==h){v.assailant=h;v.progress=0;}v.progress+=dt;h.siege={village:v,contested:false};h.attackUntil=this.time+.2;if(v.progress>=CONFIG.villageDuration){v.removed=true;this.resources.splice(i,1);const reward=villageReward(h.units.length);this.collect(h,{kind:'village',captured:true,value:reward});h.siege=null;this.effects.push({x:v.x,y:v.y,text:'VILLAGE CONQUERED +'+reward*(h.growthUntil>this.time?2:1),color:'#eec569',life:2});this.addTrace(v.x,v.y,'ruins');}}}
 addTrace(x,y,kind,color='#9e4a40'){this.traces.push({x,y,kind,color,angle:this.random()*Math.PI*2});if(this.traces.length>CONFIG.maxTraces)this.traces.splice(0,this.traces.length-CONFIG.maxTraces);}
 damage(h,amount,attacker=null){if(!h.alive)return;if(h.run)updateRun(h,this.time);const mounted=!!h.mount,before=h.units.length,{lost,leaderLost}=h.units.damage(amount);for(let i=0;i<Math.min(lost,6);i++){const f=displayedFormation(Math.max(0,visibleCount(before)-1-i),before);this.addTrace(h.x+f.x,h.y+f.y,'bones');this.effects.push({x:h.x+f.x,y:h.y+f.y,text:'',kind:'fall',faction:h.faction,color:h.color,life:.22});}if(lost&&attacker)this.spawnResource(h.x,h.y,'loot',{owner:attacker,source:h.name,ready:this.time+.12,value:lost+(leaderLost?2:0),expires:this.time+12});if(lost){if(attacker)this.notice(h,'lostSoldiers',{count:lost,name:attacker.name},'#eda29c');h.lastLoss=this.time;h.peakCount=Math.max(h.peakCount,before);}h.flash=.14;if(!h.units.length){this.lifecycle.die(h,attacker,before);this.effects.push({kind:'kingFall',x:h.x,y:h.y,faction:h.faction,mounted,facing:h.facing,life:1.4});this.fallen.push({horde:h,time:this.time});this.fallen=this.fallen.slice(-4);this.addTrace(h.x,h.y,'crown');}}

 battle(a,b,contact=1){if(!a.alive||!b.alive)return;a.attackUntil=b.attackUntil=this.time+.3;if(a===this.player||b===this.player)this.sound('battle');const ac=a.units.length,bc=b.units.length;this.addTrace((a.x+b.x)/2+(this.random()-.5)*60,(a.y+b.y)/2+(this.random()-.5)*60,'blood');this.damage(a,Math.max(.35,bc*.2)*contact*(b===this.player?this.rules.playerDamage:this.rules.botDamage)*(b.fedUntil>this.time?CONFIG.foodDamage:1),b);this.damage(b,Math.max(.35,ac*.2)*contact*(a===this.player?this.rules.playerDamage:this.rules.botDamage)*(a.fedUntil>this.time?CONFIG.foodDamage:1),a);this.effects.push({x:(a.x+b.x)/2,y:(a.y+b.y)/2,text:'',kind:'slash',angle:Math.atan2(b.y-a.y,b.x-a.x),color:'#ffe1a0',life:.3});for(const [loser,winner] of [[a,b],[b,a]])if(!loser.alive){if(winner.alive){winner.score+=100;winner.conquests++;this.sound('conquest',winner);if(!winner.run)this.lifecycle.register(winner);winner.run.kills++;updateRun(winner,this.time);if(winner===this.player)this.kills=winner.run.kills;if(winner.conquests%CONFIG.conquestsForGrowth===0){winner.growthUntil=this.time+CONFIG.growthDuration;this.sound('growth',winner);this.effects.push({x:winner.x,y:winner.y,text:'CONQUEST · GROWTH ×2',color:'#dcc6ff',life:2});}}this.effects.push({x:loser.x,y:loser.y,text:loser.name+' cayó',color:'#eec569',life:2});}}
}
